language: python
matrix:
  include:
  - python: '3.7'
    env: TOX_ENV=black,flake8,mypy,py37
    dist: xenial
    sudo: true # required workaround for https://github.com/travis-ci/travis-ci/issues/9815
  - python: '3.6'
    env: TOX_ENV=py36
  - python: '3.5'
    env: TOX_ENV=py35
  - python: '3.4'
    env: TOX_ENV=py34
  - python: '2.7'
    env: TOX_ENV=py27
  - python: 'pypy3.5'
    env: TOX_ENV=pypy3
  - python: 'pypy'
    env: TOX_ENV=pypy
cache:
  directories:
  - $HOME/.cache/pip
  - $TRAVIS_BUILD_DIR/.tox
install:
- pip install tox coveralls
script:
- tox -e $TOX_ENV -- --cov=graphql_server
after_success:
- coveralls
deploy:
  provider: pypi
  user: syrusakbary
  on:
    tags: true
